# Библиотека Numpy

### Homework

1. Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули.

2. Создайте двумерный массив 10x3, заполненный случайными значениями. В каждой строке выберите значение, наиболее близкое к 0.5.

3. Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

4. На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

5. Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

6. Сколько вы можете предложить способов округлить значения в массиве до ближайшего целого?
 
7. Написать функцию, реализующую алгоритм kNN.

    Входом в функцию является
    * train_X - матрица признаков обучающего датасета
    * train_Y - массив классов обучающего датасета
    * test_X - матрица признаков тестового датасета
    * k - число соседей
    
   Выход:
   * массив той же, что и test_X, содержащий классы для тестового датасета
   
   **Фунция должна содержать не более 1 цикла for/while!**
   **Стремитесь  обойтись как можно меньшим количеством строк кода.**
    
8. Применить kNN на выборкe ```test_images``` для разных K. Посчитать точность классификации (accuracy) и выбрать оптимальное К.

In [ ]:
#Задача 1
import numpy as np
b = np.zeros((5,5))
b[1:,:-1] = np.diag(np.arange(1,5))
b

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [ ]:
#Задача 2
a = np.random.rand(10,3)
print(a)
print(a[np.arange(10), np.argmin(abs(a - 0.5), axis = 1)])

[[0.80212931 0.99515958 0.95264434]
 [0.39349264 0.10742617 0.78942923]
 [0.37366254 0.15879685 0.74067071]
 [0.28498354 0.0915068  0.44677836]
 [0.41330256 0.1872204  0.38957941]
 [0.99338117 0.89797811 0.18267938]
 [0.01118381 0.05425659 0.81047228]
 [0.81944212 0.57656056 0.45426889]
 [0.58202098 0.78090361 0.49547939]
 [0.57533609 0.94650462 0.46307631]]
[0.80212931 0.39349264 0.37366254 0.44677836 0.41330256 0.18267938
 0.81047228 0.45426889 0.49547939 0.46307631]


In [ ]:
#Задача 3
a = np.random.rand(6,6)
b = np.divide(np.sum(a, axis = 1), a[np.arange(6), np.argmax(a, axis = 0)])
b

array([ 3.36591523, 10.29203072,  3.48755113, 17.04754629,  4.22859737,
        7.78693831])

In [ ]:
#Задача 4
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
ind = np.where(x == 0)[0] + 1
print(np.max(x[ind[ind < np.size(x)]]))

5


In [ ]:
#Задача 5
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
a = unique, counts = np.unique(i, return_counts=True)
x[unique] += counts
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [ ]:
#Задача 6
a - массив
1) np.around(a, 0)
2) np.rint()
3) писать алгоритм ищущий дробные части, после сравнение с 0.5 и +- в зависимости от этого

In [48]:
#Задача 7 (реализовать kNN)
def classifyKNN (train_X, train_Y, test_X, k):
  predictions = []
  for test in test_X:
    #если train_X - некоторая матрица (пусть координаты из R3), каждому элементу в ней отвечает строка,
    #тогда dist - столбец из расстояний от каждого из элементов train_X до test
    dist = np.sum(np.sqrt((test - train_X) ** 2), axis = 1);
    #сортирую по расстоянию индексы и отбираю "принадлежность к классу" первых k элементов
    labels = train_Y[np.argsort(dist)[:k]]
    #добавляю встречающийся наиболее часто
    a = unique, counts = np.unique(labels, return_counts=True)
    predictions.append(unique[np.argsort(counts)][-1:])

  return np.array(predictions)

In [49]:
#Задача 8
from sklearn.datasets import fetch_openml
import numpy as np


#Загрузка может занять около минуты
images, labels = fetch_openml('mnist_784', return_X_y=True, as_frame=False)

In [50]:
train_size = 1000
train_images = images[:train_size]
train_labels = labels[:train_size]
test_size = 100
test_images = images[-test_size:]
test_labels = labels[-test_size:]

accuracy = np.zeros(50)
for k in range(1,50):
  a = classifyKNN(train_images, train_labels ,test_images, k).reshape(1,-1)[0]
  accuracy[k] = np.sum(test_labels == a)/test_size
print(accuracy[1:])

[0.94 0.89 0.9  0.89 0.88 0.88 0.86 0.88 0.89 0.87 0.87 0.87 0.88 0.87
 0.86 0.85 0.85 0.85 0.84 0.84 0.83 0.84 0.83 0.83 0.82 0.81 0.83 0.82
 0.82 0.82 0.82 0.85 0.83 0.83 0.82 0.81 0.8  0.81 0.8  0.79 0.78 0.78
 0.77 0.78 0.77 0.79 0.78 0.78 0.77]
